import { useEffect } from "react";

// Font options derived from public/index.html <link> tags, sorted alphabetically
export const fontOptions = [
  { value: "Abril Fatface", label: "Abril Fatface" },
  { value: "Allura", label: "Allura" },
  { value: "Amatic SC", label: "Amatic SC" },
  { value: "Anton", label: "Anton" },
  { value: "Architects Daughter", label: "Architects Daughter" },
  { value: "Arimo", label: "Arimo" },
  { value: "Asap", label: "Asap" },
  { value: "Barlow", label: "Barlow" },
  { value: "Bebas Neue", label: "Bebas Neue" },
  { value: "Bitter", label: "Bitter" },
  { value: "Bree Serif", label: "Bree Serif" },
  { value: "Cabin", label: "Cabin" },
  { value: "Cardo", label: "Cardo" },
  { value: "Caveat", label: "Caveat" },
  { value: "Cinzel", label: "Cinzel" },
  { value: "Chewy", label: "Chewy" },
  { value: "Comfortaa", label: "Comfortaa" },
  { value: "Courier New", label: "Courier New" },
  { value: "Crimson Text", label: "Crimson Text" },
  { value: "Cuprum", label: "Cuprum" },
  { value: "Dancing Script", label: "Dancing Script" },
  { value: "Dosis", label: "Dosis" },
  { value: "Droid Sans", label: "Droid Sans" },
  { value: "Exo 2", label: "Exo 2" },
  { value: "Fira Sans", label: "Fira Sans" },
  { value: "Fjalla One", label: "Fjalla One" },
  { value: "Francois One", label: "Francois One" },
  { value: "Fredoka One", label: "Fredoka One" },
  { value: "Georgia", label: "Georgia" },
  { value: "Gilda Display", label: "Gilda Display" },
  { value: "Gloria Hallelujah", label: "Gloria Hallelujah" },
  { value: "Great Vibes", label: "Great Vibes" },
  { value: "Handlee", label: "Handlee" },
  { value: "Hammersmith One", label: "Hammersmith One" },
  { value: "Heebo", label: "Heebo" },
  { value: "IM Fell English SC", label: "IM Fell English SC" },
  { value: "Inconsolata", label: "Inconsolata" },
  { value: "Indie Flower", label: "Indie Flower" },
  { value: "Istok Web", label: "Istok Web" },
  { value: "Jaldi", label: "Jaldi" },
  { value: "Josefin Sans", label: "Josefin Sans" },
  { value: "Jura", label: "Jura" },
  { value: "Kanit", label: "Kanit" },
  { value: "Karla", label: "Karla" },
  { value: "Khand", label: "Khand" },
  { value: "Kreon", label: "Kreon" },
  { value: "Lato", label: "Lato" },
  { value: "Lekton", label: "Lekton" },
  { value: "Libre Baskerville", label: "Libre Baskerville" },
  { value: "Limelight", label: "Limelight" },
  { value: "Lobster", label: "Lobster" },
  { value: "Lobster Two", label: "Lobster Two" },
  { value: "Lora", label: "Lora" },
  { value: "Luckiest Guy", label: "Luckiest Guy" },
  { value: "Maiden Orange", label: "Maiden Orange" },
  { value: "Marck Script", label: "Marck Script" },
  { value: "Maven Pro", label: "Maven Pro" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Merriweather Sans", label: "Merriweather Sans" },
  { value: "Monda", label: "Monda" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Muli", label: "Muli" },
  { value: "Noto Sans", label: "Noto Sans" },
  { value: "Nunito", label: "Nunito" },
  { value: "Noticia Text", label: "Noticia Text" },
  { value: "Old Standard TT", label: "Old Standard TT" },
  { value: "Oldenburg", label: "Oldenburg" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Orbitron", label: "Orbitron" },
  { value: "Oswald", label: "Oswald" },
  { value: "Ovo", label: "Ovo" },
  { value: "Padauk", label: "Padauk" },
  { value: "Pacifico", label: "Pacifico" },
  { value: "Parisienne", label: "Parisienne" },
  { value: "Passion One", label: "Passion One" },
  { value: "Pathway Gothic One", label: "Pathway Gothic One" },
  { value: "Patua One", label: "Patua One" },
  { value: "Permanent Marker", label: "Permanent Marker" },
  { value: "Philosopher", label: "Philosopher" },
  { value: "Pinyon Script", label: "Pinyon Script" },
  { value: "Play", label: "Play" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Poiret One", label: "Poiret One" },
  { value: "Poppins", label: "Poppins" },
  { value: "Prata", label: "Prata" },
  { value: "Press Start 2P", label: "Press Start 2P" },
  { value: "Prociono", label: "Prociono" },
  { value: "PT Sans", label: "PT Sans" },
  { value: "Puritan", label: "Puritan" },
  { value: "Qwigley", label: "Qwigley" },
  { value: "Quicksand", label: "Quicksand" },
  { value: "Radley", label: "Radley" },
  { value: "Raleway", label: "Raleway" },
  { value: "Rationale", label: "Rationale" },
  { value: "Red Hat Display", label: "Red Hat Display" },
  { value: "Reenie Beanie", label: "Reenie Beanie" },
  { value: "Righteous", label: "Righteous" },
  { value: "Rokkitt", label: "Rokkitt" },
  { value: "Ropa Sans", label: "Ropa Sans" },
  { value: "Rosario", label: "Rosario" },
  { value: "Rubik", label: "Rubik" },
  { value: "Russo One", label: "Russo One" },
  { value: "Sacramento", label: "Sacramento" },
  { value: "Sail", label: "Sail" },
  { value: "Sansita", label: "Sansita" },
  { value: "Sansita Swashed", label: "Sansita Swashed" },
  { value: "Sarabun", label: "Sarabun" },
  { value: "Satisfy", label: "Satisfy" },
  { value: "Schoolbell", label: "Schoolbell" },
  { value: "Seaweed Script", label: "Seaweed Script" },
  { value: "Shadows Into Light", label: "Shadows Into Light" },
  { value: "Shrikhand", label: "Shrikhand" },
  { value: "Signika", label: "Signika" },
  { value: "Six Caps", label: "Six Caps" },
  { value: "Slabo 27px", label: "Slabo 27px" },
  { value: "Smokum", label: "Smokum" },
  { value: "Source Sans Pro", label: "Source Sans Pro" },
  { value: "Special Elite", label: "Special Elite" },
  { value: "Spinnaker", label: "Spinnaker" },
  { value: "Staatliches", label: "Staatliches" },
  { value: "Stalemate", label: "Stalemate" },
  { value: "Stint Ultra Condensed", label: "Stint Ultra Condensed" },
  { value: "Stix Two Text", label: "Stix Two Text" },
  { value: "Sunflower", label: "Sunflower" },
  { value: "Supermercado One", label: "Supermercado One" },
  { value: "Syncopate", label: "Syncopate" },
  { value: "Tangerine", label: "Tangerine" },
  { value: "Tauri", label: "Tauri" },
  { value: "Telex", label: "Telex" },
  { value: "Text Me One", label: "Text Me One" },
  { value: "Times New Roman", label: "Times New Roman" },
  { value: "Tienne", label: "Tienne" },
  { value: "Titillium Web", label: "Titillium Web" },
  { value: "Trade Winds", label: "Trade Winds" },
  { value: "Trirong", label: "Trirong" },
  { value: "Trochut", label: "Trochut" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "Ubuntu Condensed", label: "Ubuntu Condensed" },
  { value: "Unica One", label: "Unica One" },
  { value: "Unkempt", label: "Unkempt" },
  { value: "Varela Round", label: "Varela Round" },
  { value: "Verdana", label: "Verdana" },
  { value: "Vidaloka", label: "Vidaloka" },
  { value: "Volkhov", label: "Volkhov" },
  { value: "VT323", label: "VT323" },
  { value: "Wallpoet", label: "Wallpoet" },
  { value: "Wendy One", label: "Wendy One" },
  { value: "Wire One", label: "Wire One" },
  { value: "Work Sans", label: "Work Sans" },
  { value: "Yanone Kaffeesatz", label: "Yanone Kaffeesatz" },
  { value: "Yeseva One", label: "Yeseva One" },
  { value: "ZCOOL QingKe HuangYou", label: "ZCOOL QingKe HuangYou" },
  { value: "ZCOOL XiaoWei", label: "ZCOOL XiaoWei" },
  { value: "Zilla Slab", label: "Zilla Slab" },
];

// Hook to dynamically load a font from Google Fonts (optional, as index.html preloads fonts)
export const useFontLoader = (fontFamily: string) => {
  useEffect(() => {
    const link = document.createElement("link");
    link.href = `https://fonts.googleapis.com/css2?family=${fontFamily.replace(
      / /g,
      "+"
    )}:wght@400&display=swap`;
    link.rel = "stylesheet";
    document.head.appendChild(link);
    console.log(`Loading font: ${fontFamily}`);
    return () => document.head.removeChild(link);
  }, [fontFamily]);
};